### ISSUE TITLE
add dist source

### ISSUE THREAD

**Issue by SuggeElson** [oliver-j/jcolumn#1]
Hello, great plugin. 
Can you make a dist folder and put a jcolumn.js and jcolumn.min.js without a version number.
Currently, I add this plugin with bower as depency and is hard to update manual include path every time like jcolumn-0.2.0.jquery.min.js

**Comment by oliver-j** [comment]
Sorry for the late respond I am not sure, if there is something missing in jColumn. 

But if there is going be a new version I will add a dist folder with files which doesn't have a version number related name.

**Comment by oliver-j** [comment]
Fixed with 0.2.5
